---
meta:
  blobstore:
    user: blobstore
    password: (( vault meta.vault "/blobstore/creds:password" ))
    secret:   (( vault meta.vault "/blobstore/creds:secret" ))
  certs:
    blobstore:
      ca_cert:  (( vault meta.vault "/cf_internal/certs/ca:certificate" ))
      cert:     (( vault meta.vault "/cf_internal/certs/blobstore_tls:certificate" ))
      key:      (( vault meta.vault "/cf_internal/certs/blobstore_tls:key" ))

  blobstore_config:
    blobstore_type: webdav
    webdav_config:
      public_endpoint: (( concat "https://blobstore." params.system_domain ))
      private_endpoint: https://blobstore.service.cf.internal:4443
      username: (( grab meta.blobstore.user ))
      password: (( grab meta.blobstore.password ))
      ca_cert:  (( grab meta.certs.blobstore.ca_cert ))

params:
  blobstore_vm_type:   blobstore
  blobstore_disk_pool: blobstore

instance_groups:
  - (( insert after "nats" ))
  - name: blobstore
    instances: 1
    persistent_disk_type: (( grab params.blobstore_disk_pool ))
    vm_type: (( grab params.blobstore_vm_type ))
    azs: (( grab params.availability_zones || meta.default.azs ))
    stemcell: default
    networks:
      - name: (( grab params.cf_internal_network ))
    jobs:
      - name: blobstore
        release: capi
        properties:
          system_domain: (( grab params.system_domain ))
          blobstore:
            admin_users:
              - username: (( grab meta.blobstore.user ))
                password: (( grab meta.blobstore.password ))
            port: 8080
            secure_link:
              secret: (( grab meta.blobstore.secret ))
            tls:
              port: 4443
              ca_cert:     (( grab meta.certs.blobstore.ca_cert ))
              cert:        (( grab meta.certs.blobstore.cert ))
              private_key: (( grab meta.certs.blobstore.key ))

      - name: route_registrar
        release: routing
        properties:
          route_registrar:
            routes:
              - name: blobstore
                port: 8080
                registration_interval: 20s
                tags:
                  component: blobstore
                uris:
                  - (( concat "blobstore." params.system_domain ))
