---
addons:
  - (( append ))
  - name: loggregator_agent
    include:
      stemcell:
        - os: ubuntu-xenial

    exclude:
      jobs:
        - { release: cf-smoke-tests, name: smoke_tests }

    jobs:
      - name: loggregator_agent
        release: loggregator-agent
        properties:
          loggregator:
            tls:
              ca_cert: (( grab meta.certs.loggregator.ca ))
              agent: (( grab meta.certs.loggregator.metron.server ))
          metron_agent:
            deployment: (( grab name ))
          metron_endpoint:
            shared_secret: (( grab meta.loggregator.endpoint_secret ))
          metrics:
            server_name:  loggregator_agent_metrics
            ca_cert: (( grab meta.certs.prometheus.ca ))
            cert:    (( grab meta.certs.prometheus.loggregator_agent_metrics.cert ))
            key:     (( grab meta.certs.prometheus.loggregator_agent_metrics.key ))
