releases:
  - name:    bpm
    version: "1.1.5"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" releases.bpm.version ))
    sha1:    e612e88543012ae5d376dd3746159d5abe748076

  - name:    capi
    version: "1.88.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=" releases.capi.version ))
    sha1:    7a7ef183de3252724b6f8e6ca39ad7cf4995fe27

  - name:    cf-networking
    version: "2.27.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-networking-release?v=" releases.cf-networking.version ))
    sha1:    1249e8140449126a9eb6102218c89eb1196c649e

  - name:    cf-smoke-tests
    version: "40.0.123"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-smoke-tests-release?v=" releases.cf-smoke-tests.version ))
    sha1:    aeea22d0d7003d69b1d6154bae41360f821be420

  - name:    cflinuxfs3
    version: "0.150.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=" releases.cflinuxfs3.version ))
    sha1:    6421766b2120009c6d422c4b1ed5a12c4290eda4

  - name:    cf-cli
    version: "1.22.0"
    url:     (( concat "https://bosh.io/d/github.com/bosh-packages/cf-cli-release?v=" releases.cf-cli.version ))
    sha1:    ccdd798cc523f64037e01e0a888a206ceb018536

  - name:    diego
    version: "2.41.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/diego-release?v=" releases.diego.version ))
    sha1:    8a183683f26ba982eda1dbeba7f55edc9a1059b0

  - name:    garden-runc
    version: "1.19.9"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=" releases.garden-runc.version ))
    sha1:    1c678e1c7a3506c0e408860571560081c15e3c6d

  - name:    loggregator
    version: "106.2.1"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=" releases.loggregator.version ))
    sha1:    b0758449cb7bf683d88375e5b3f230c70ce4d6ec

  - name:    loggregator-agent
    version: "5.2.2"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=" releases.loggregator-agent.version ))
    sha1:    da2da3417936921a692bda4fa5390cb113e137dd

  - name:    log-cache
    version: "2.6.1"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=" releases.log-cache.version ))
    sha1:    a8b057ce9a942788dfbb356904e5a793954c6411

  - name:    nats
    version: "28"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nats-release?v=" releases.nats.version ))
    sha1:    64b143778b4cd741970798e32523d564d429d62a

  - name:    routing
    version: "0.195.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/routing-release?v=" releases.routing.version ))
    sha1:    2b899d7bd6d35b9aacb410f0343989e82397d86d

  - name:    statsd-injector
    version: "1.11.4"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/statsd-injector-release?v=" releases.statsd-injector.version ))
    sha1:    255e718ed424a8e3d6ccfe8a4c5c5c0718fced17

  - name:    cf-syslog-drain
    version: "10.2.2"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-syslog-drain-release?v=" releases.cf-syslog-drain.version ))
    sha1:    e899847cd564cb53232961cc1621e3bbec1189e1

  - name:    uaa
    version: "74.12.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=" releases.uaa.version ))
    sha1:    5fdd99addec2aebe521a468dba0bcd52e66c86c6

  - name:    silk
    version: "2.27.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/silk-release?v=" releases.silk.version ))
    sha1:    8c3a88affb84cbc28bf659292819c8c0ad23abe7

  - name:    bosh-dns-aliases
    version: "0.0.3"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=" releases.bosh-dns-aliases.version ))
    sha1:    b0d0a0350ed87f1ded58b2ebb469acea0e026ccc
