--- # overrides: basic overrides for genesis compatibility
exodus:
  cf_deployment_version: manifest_version

  admin_username: admin
  admin_password: ((cf_admin_password))
  base_domain:    (( grab params.base_domain ))
  system_domain:  (( grab params.system_domain ))
  app_domains:    (( grab params.app_domains ))
  app_domain:     (( grab params.app_domain ))

  edge_network:    (( grab params.cf_edge_network || params.network ))
  core_network:    (( grab params.cf_core_network || params.network ))
  runtime_network: (( grab params.cf_runtime_network || params.network ))

  vaulted_uaa_clients: (( concat meta.vault "/uaa/client_secrets:firehose" ))

  system_org:   system
  system_space: system

# BOSH Variables - used to populate ((variables))
bosh-variables:
  system_domain:   (( grab params.system_domain ))
  deployment_name: (( grab name ))
  network_name:    (( grab params.network ))

meta:
  app_domains:
    - ((system_domain))
  default_apps_domains: (( grab params.apps_domains || meta.app_domains ))
  internal_app_domains: []
  default_azs: [z1, z2, z3]

params:
  network: default

  base_domain: (( param "What is the base domain for this Cloud Foundry?" ))
  system_domain: (( concat "system." params.base_domain ))
  app_domains: (( grab meta.default_apps_domains meta.internal_app_domains ))
  apps_domain: (( grab params.app_domains[0] ))


name: (( grab params.name ))

# CAs should last 10 years instead of the default Credhub 1y
variables:
- { name: silk_ca,                    options: { duration: 3650 } }
- { name: network_policy_ca,          options: { duration: 3650 } }
- { name: service_cf_internal_ca,     options: { duration: 3650 } }
- { name: loggregator_ca,             options: { duration: 3650 } }
- { name: log_cache_ca,               options: { duration: 3650 } }
- { name: router_ca,                  options: { duration: 3650 } }
- { name: routing_api_ca,             options: { duration: 3650 } }
- { name: uaa_ca,                     options: { duration: 3650 } }
- { name: application_ca,             options: { duration: 3650 } }
- { name: diego_instance_identity_ca, options: { duration: 3650 } }
- { name: credhub_ca,                 options: { duration: 3650 } }
- { name: metric_scraper_ca,          options: { duration: 3650 } }