---
addons:
  - name: forwarder_agent
    include:
      stemcell:
        - os: ubuntu-xenial
    jobs:
      - name: loggr-forwarder-agent
        release: loggregator-agent
        properties:
          tls:
            ca_cert: (( grab meta.certs.loggregator.ca.certificate ))
            cert:    (( vault meta.vault "loggregator.forwarder_agent:certificate" ))
            key:     (( vault meta.vault "loggregator.forwarder_agent:key" ))

  - name: udp_forwarder
    include:
      stemcell:
        - os: ubuntu-xenial
    jobs:
      - name: loggr-udp-forwarder
        release: loggregator-agent
        properties:
          loggregator:
            ingress_port: 3459
            tls:
              ca_cert: (( grab meta.certs.loggregator.ca ))
              cert:    (( grab meta.certs.loggregator.metron.server.cert ))
              key:     (( grab meta.certs.loggregator.metron.server.key ))

  - name: loggregator_agent
    jobs:
      - name: loggregator_agent
        properties:
          grpc_port:   3459
          disable_udp: true
          # metrics:
          #   server_name: loggregator_agent_metrics
          #   ca_cert:     (( grab meta. ))
          #   cert:        (( grab meta. ))
          #   key:         (( grab meta. ))