---
addons:
  - name: forwarder_agent
    include:
      stemcell:
        - os: ubuntu-xenial
    jobs:
      - name: loggr-forwarder-agent
        release: loggregator-agent
        properties:
          tls:
            ca_cert: (( grab meta.certs.loggregator.ca ))
            cert:    (( grab meta.certs.loggregator.forwarder_agent.cert ))
            key:     (( grab meta.certs.loggregator.forwarder_agent.key ))
          metrics:
            server_name:  forwarder_agent_metrics
            ca_cert: (( grab meta.certs.prometheus.ca ))
            cert:    (( grab meta.certs.prometheus.forwarder_agent_metrics.cert ))
            key:     (( grab meta.certs.prometheus.forwarder_agent_metrics.key ))

  - name: udp_forwarder
    include:
      stemcell:
        - os: ubuntu-xenial
    jobs:
      - name: loggr-udp-forwarder
        release: loggregator-agent
        properties:
          loggregator:
            ingress_port: 3459
            tls:
              ca_cert: (( grab meta.certs.loggregator.ca ))
              cert:    (( grab meta.certs.loggregator.metron.server.cert ))
              key:     (( grab meta.certs.loggregator.metron.server.key ))
            metrics:
              server_name:  loggr_udp_forwarder
              ca_cert: (( grab meta.certs.prometheus.ca ))
              cert:    (( grab meta.certs.prometheus.loggr_udp_forwarder.cert ))
              key:     (( grab meta.certs.prometheus.loggr_udp_forwarder.key ))

  - name: loggregator_agent
    jobs:
      - name: loggregator_agent
        properties:
          grpc_port:   3459
          disable_udp: true
          